### ISSUE TITLE
Should we be using admin styles for this application?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/content-performance-manager#16]
From a discussion with @fofr , we were thinking it might make more sense for this application to be similar to our other admin/publishing applications.

https://github.com/alphagov/govuk_admin_template

Caught up with @selfthinker and she said the idea was that this application become public at some point similar to https://github.com/alphagov/info-frontend however we should decide if this is realistic and decide.

**Comment by selfthinker** [comment]
I discussed this with our product manager and with @pmanrubia. There are three reasons why we'd like to keep it as it is:

1. Our default is to be open, so the intention is definitely to make it open. If that will be on gov.uk or somewhere else still needs to be decided (probably in a few months). Ben said that in some nice, convincing words I cannot remember. I will ask him to either update this or remind me.

2. Even if this turns out to be hidden somewhere that doesn't mean we would need to use the admin template. There are other GDS projects which use Elements but are behind a login and/or not on gov.uk.

3. We don't know enough about where this project is going. There is the possibility that the frontend will be deleted at some point and we'll only provide APIs. In any case, this is an alpha and should be treated as "throwawayable".

The only reason left for me to switch to the admin template could be if it provided something that we need. But I don't think that is the case with what we plan to do.

**Comment by pmanrubia** [comment]
We have gathered more information about this application and its place within GOV.UK. We have finally decided to use the admin template and expose and API that could be consumed from any fronted app. I am closing this issue. 

See https://github.com/alphagov/content-performance-manager/pull/65

Thank you @selfthinker  @theleebriggs @nickcolley for your work on this.
